# Generated by Django 5.2.1 on 2025-05-23 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presensi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='presensi',
            name='guru',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='presensi_guru', to='presensi.abstractuser'),
        ),
        migrations.AlterField(
            model_name='abstractuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('staff', 'Staff'), ('guru', 'Guru'), ('siswa', 'Siswa')], default='employee', max_length=20),
        ),
        migrations.CreateModel(
            name='Kelas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50)),
                ('siswa', models.ManyToManyField(related_name='kelas_siswa', to='presensi.abstractuser')),
                ('wali_kelas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wali_kelas', to='presensi.abstractuser')),
            ],
        ),
        migrations.AddField(
            model_name='presensi',
            name='kelas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='presensi', to='presensi.kelas'),
        ),
        migrations.CreateModel(
            name='MataPelajaran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('guru', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mapel_guru', to='presensi.abstractuser')),
                ('kelas', models.ManyToManyField(related_name='mata_pelajaran', to='presensi.kelas')),
            ],
        ),
        migrations.AddField(
            model_name='presensi',
            name='mata_pelajaran',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='presensi', to='presensi.matapelajaran'),
        ),
    ]
